import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://inclua2.ipea.gov.br/pre-diagnostico');
  await page.getByRole('link', { name: 'Diagnóstico online' }).click();
  await page.getByLabel('Qual oferta pública será objeto de avaliação? Isto é, que caso concreto de política pública, programa, projeto, ação ou serviço será submetido ao diagnóstico?').click();
  await page.getByLabel('Qual oferta pública será objeto de avaliação? Isto é, que caso concreto de política pública, programa, projeto, ação ou serviço será submetido ao diagnóstico?').fill('Plataforma para jogos educacionais');
  await page.getByLabel('Qual(is) segmento(s) do público serão tomados como foco de atenção? O diagnóstico deve ter como foco as formas específicas de relação entre a oferta pública identificada no item acima e os o(s) público(s) específico(s) a serem considerados.').click();
  await page.getByLabel('Qual(is) segmento(s) do público serão tomados como foco de atenção? O diagnóstico deve ter como foco as formas específicas de relação entre a oferta pública identificada no item acima e os o(s) público(s) específico(s) a serem considerados.').fill('foco em jovens que queiram aprender a programar ');
  await page.locator('#btnCategoria0').click();
  await page.locator('#btnCategoria0').click();
  await page.getByText('Acessibilidade urbana').click();
  await page.getByText('Educação').click();
  await page.getByText('Acessibilidade digital').click();
  await page.locator('#btnCategoria0').click();
  await page.getByRole('listitem').filter({ hasText: 'Sim' }).click();
  await page.locator('.range-merker > .radio > li:nth-child(2) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.locator('div:nth-child(3) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.getByText('12345').nth(3).click();
  await page.getByText('12345').nth(3).click();
  await page.getByText('7').click();
  await page.getByRole('button', { name: 'indicador 1.2' }).click();
  await page.locator('li > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > .radio > li > div').first().click();
  await page.locator('div:nth-child(3) > .box-items > .radio > li > div').first().click();
  await page.getByRole('listitem').filter({ hasText: '3' }).locator('div').click();
  await page.getByText('7').click();
  await page.getByRole('button', { name: 'dimensão 2' }).click();
  await page.locator('li:nth-child(3) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.getByRole('listitem').filter({ hasText: 'Sim' }).locator('div').click();
  await page.locator('div:nth-child(4) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.getByText('7').click();
  await page.getByRole('button', { name: 'indicador 2.2' }).click();
  await page.locator('li:nth-child(2) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(4) > div').click();
  await page.locator('div:nth-child(3) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.locator('div:nth-child(4) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.getByText('8').click();
  await page.getByRole('button', { name: 'dimensão 3' }).click();
  await page.locator('li:nth-child(3) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(4) > div').click();
  await page.getByRole('button', { name: 'Enviar Diagnóstico Parcial' }).click();
  await page.locator('li:nth-child(2) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(4) > div').click();
  await page.getByRole('button', { name: 'indicador 3.3' }).click();
  await page.locator('li:nth-child(5) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.locator('div:nth-child(3) > .box-items > div > .range-merker > .radio > li:nth-child(4) > div').click();
  await page.getByText('8').click();
  await page.getByRole('button', { name: 'dimensão 4' }).click();
  await page.locator('li:nth-child(2) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li').first().click();
  await page.locator('div:nth-child(3) > .box-items > div > .range-merker > .radio > li > div').first().click();
  await page.locator('div:nth-child(4) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.getByRole('listitem').filter({ hasText: 'Não' }).locator('div').click();
  await page.locator('div:nth-child(6) > .box-items > div > .range-merker > .radio > li > div').first().click();
  await page.locator('div:nth-child(7) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.getByRole('listitem').filter({ hasText: '0' }).locator('div').click();
  await page.locator('div:nth-child(8) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.locator('div').filter({ hasText: '2' }).nth(1).click();
  await page.getByRole('button', { name: 'indicador 4.2' }).click();
  await page.locator('li:nth-child(3) > div').first().click();
  await page.locator('li:nth-child(3) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.locator('div:nth-child(3) > .box-items > div > .range-merker > .radio > li:nth-child(4) > div').click();
  await page.getByText('4', { exact: true }).nth(3).click();
  await page.getByRole('button', { name: 'indicador 4.3' }).click();
  await page.locator('li:nth-child(3) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(2) > div').click();
  await page.locator('div:nth-child(3) > .box-items > div > .range-merker > .radio > li:nth-child(5) > div').click();
  await page.locator('div:nth-child(4) > .box-items > div > .range-merker > .radio > li > div').first().click();
  await page.locator('div:nth-child(5) > .box-items > div > .range-merker > .radio > li > div').first().click();
  await page.locator('div:nth-child(6) > .box-items > div > .range-merker > .radio > li:nth-child(2) > div').click();
  await page.locator('div').filter({ hasText: '5' }).nth(1).click();
  await page.getByRole('button', { name: 'dimensão 5' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Não' }).locator('div').click();
  await page.getByText('12345').first().click();
  await page.locator('div:nth-child(3) > .box-items > div > .range-merker > .radio > li > div').first().click();
  await page.locator('div:nth-child(4) > .box-items > div > .range-merker > .radio > li > div').first().click();
  await page.getByText('9').click();
  await page.getByRole('button', { name: 'indicador 5.2' }).click();
  await page.locator('li:nth-child(5) > div').first().click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.locator('div:nth-child(3) > .box-items > div > .range-merker > .radio > li:nth-child(3) > div').click();
  await page.locator('div:nth-child(4) > .box-items > div > .range-merker > .radio > li:nth-child(4) > div').click();
  await page.getByText('8').click();
  await page.getByRole('button', { name: 'indicador 5.3' }).click();
  await page.locator('li:nth-child(5) > div').first().click();
  await page.locator('li:nth-child(5) > div').first().click();
  await page.getByRole('listitem').filter({ hasText: 'Não' }).locator('div').click();
  await page.getByText('5', { exact: true }).nth(2).click();
  await page.getByRole('button', { name: 'Enviar Diagnóstico Parcial' }).click();
  await page.locator('div:nth-child(2) > .box-items > div > .range-merker > .radio > li:nth-child(4) > div').click();
  await page.getByRole('paragraph').filter({ hasText: 'Indicações de 33 recursos para intervenção' }).locator('svg').click();
});